# Jykell configuration
markdown: redcarpet
redcarpet:
  extensions:
  - fenced_code_blocks
  - footnotes
highlighter: pygments
paginate: 5
language: 'en-uk'
timezone: 'Asia/Kolkata'
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: ''

# Website info
name: 'Blog | Manidesto'
description: "Android · Development · Design"

# Author's info
author: 'Manideep Polireddi'
# edit 'categories' in the front matter of every post to match this username
username: manidesto
bio: 'Android developer · Design Enthusiast'
location: 'Mumbai, India'
url: 'http://manidesto.github.io/'
image: 'assets/images/manidesto.png'

short_url: 'manidesto.github.io/'
google_analytics: UA-57441445-3
#disqus: username

# Permalinks
permalink: :title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...
